### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by marianomd** [tovask/ESP32-CAM#1]
Hello, this seems very interesting, have you tried to use it with iNav?

**Comment by tovask** [comment]
No, I didn't try it with iNav, but I think it can work, if you manage to calibrate it well.

**Comment by hqbao** [comment]
Hi, how many FPS/resolution we can archive?

**Comment by tovask** [comment]
Hi, sorry for not answering, I'm no longer doing this project, I don't know the answer for your question.
